#!/usr/bin/env perl
use Mojolicious::Lite;
use Data::Dumper;
use v5.20;
use experimental 'signatures';

our %tasks;
helper tasks => sub($c) {
    # name => { fulltext, fullurl }
    unless (%tasks) {
        my $url = Mojo::URL->new('http://rosettacode.org/mw/index.php')->query(
            'title'          => 'Special:Ask',
            'sort[0]'        => 'Modification_date',
            'p[sort]'        => 'Modification_date',
            'q'              => '[[Is task::true]]',
            'p[format]'      => 'json',
            'p[headers]'     => 'show',
            'p[limit]'       => '500',
            'order[0]'       => 'DESC',
            'p[link]'        => 'all',
            'order_num'      => 'ASC'
       );
       my $tx = $c->ua->get($url);
       my $got = $tx->res->json;
       %tasks = %{ $got->{results} };
   }
   \%tasks;
};

helper task_names => sub($c) {
    return sort keys %{ $c->tasks };
};

helper task => sub($c,$name) {
    return $c->tasks->{$name};
};

get '/' => sub($c) {
    $c->render(template => 'index');
};

get '/task/*name' => sub($c) {
    my $task = $c->stash('name');
    my $page = $c->ua->get($c->task($task)->{fullurl})->res;
    my @langs = $page->dom->find('span.mw-headline')
        ->map(sub { shift->attr('id') })->each;
    $c->render(template => 'task', langs => \@langs);
} => 'task';

get '/lang/:lang/:task' => [ lang => '\d+' ] => sub($c) {
    my $task = $c->stash('task');
    my $url = Mojo::URL->new('http://rosettacode.org/mw/index.php')
        ->query(title => $task, action => 'edit', section => $c->stash('lang'));
    my $page = $c->ua->get($url)->res;
    my $markdown = $page->dom->at('textarea#wpTextbox1')->text;
    $markdown =~ /<lang ([^>]+)>(.*)$/mxs;
    my $language = $1;
    my $code = $2;
    $code =~ s/^(.*)
        \{\{
        out
        \}\}
        .*$
        /$1/mxs;
    $c->render(template => 'langtask', code => $code, page => $page, language => $language);
} => 'langtask';

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Gletta';
<ol>
% for my $t (task_names) {
<li><%= link_to 'task', { name => $t } => begin %><%= $t %><%= end %>
% }
</ol>
@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>

@@ task.html.ep
% layout 'default';
<h1><%= $name %></h1>
<a target="_blank" href="<%= task($name)->{fullurl} %>">rosettacode</a>
<ol>
% my $i = 0;
% for my $l (@$langs) {
<li><%= link_to 'langtask' => { lang => ++$i, task => $name } => begin %><%= $l %><%= end %>
% }
</ol>

@@ langtask.html.ep
% layout 'default';
<h1><%= $task %></h1>
<h2><%= $language %></h2>
<pre style='border:1px solid black;'>
%= $code
</pre>

