#!/usr/bin/env perl
use Mojolicious::Lite;
use Data::Dumper;
use v5.20;
use experimental 'signatures';

our %tasks;
helper tasks => sub($c) {
    # name => { fulltext, fullurl }
    unless (%tasks) {
        my $url = Mojo::URL->new('http://rosettacode.org/mw/index.php')->query(
            'title'          => 'Special:Ask',
            'sort[0]'        => 'Modification_date',
            'p[sort]'        => 'Modification_date',
            'q'              => '[[Is task::true]]',
            'p[format]'      => 'json',
            'p[headers]'     => 'show',
            'p[limit]'       => '500',
            'order[0]'       => 'DESC',
            'p[link]'        => 'all',
            'order_num'      => 'ASC'
       );
       my $tx = $c->ua->get($url);
       my $got = $tx->res->json;
       %tasks = %{ $got->{results} };
   }
   %tasks;
};

helper task_names => sub($c) {
    my %tasks = $c->tasks;
    return sort keys %tasks;
};

get '/' => sub($c) {
    $c->render(template => 'index');
};

get '/task/*name' => sub($c) {
    $c->render(template => 'task');
} => 'task';

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Gletta';
<ol>
% for my $t (task_names) {
<li><%= link_to 'task', { name => $t } => begin %><%= $t %><%= end %>
% }
</ol>
@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>

@@ task.html.ep
% layout 'default';

